# Generated by Django 5.2.14 on 2026-05-24 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_index', models.IntegerField()),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('easiness', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('due_date', models.DateField()),
                ('last_quality', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to='results.result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sr_cards',
                'indexes': [models.Index(fields=['user', 'due_date'], name='sr_cards_user_id_b6fc46_idx')],
                'unique_together': {('user', 'result', 'card_index')},
            },
        ),
    ]
