services:
  - type: web
    name: studyforge-api
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn studyforge_django.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.14.3"
    packages:
      - tesseract-ocr
      - tesseract-ocr-eng
      - poppler-utils