# Generated by Django 5.2.14 on 2026-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ready', 'Ready'), ('review', 'Review'), ('streak', 'Streak'), ('insight', 'Insight'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
